{"uid":"cf6d1a844d9471c0","name":"test_send_message_2_add_remove_reactions_and_cleanup[chrome]","fullName":"test_DiscordFrontEnd.TestDiscordMessageActions#test_send_message_2_add_remove_reactions_and_cleanup","historyId":"b4555d1507a1b8305e77637bd4ae3e13","time":{"start":1730127410145,"stop":1730127410145,"duration":0},"status":"failed","statusMessage":"AssertionError: Не удалось перейти на https://discord.com/channels/@me","statusTrace":"self = <login_page.LoginPage object at 0x7faac0ea7ca0>\n\n    @allure.step(\"Проверка перехода на страницу каналов\")\n    def verify_login_success(self):\n        try:\n>           self.wait_for_url_to_be(LoginPage.CHANNELS_URL, timeout=20)\n\nlogin_page.py:58: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nlogin_page.py:93: in wait_for_url_to_be\n    WebDriverWait(self.driver, timeout).until(EC.url_to_be(url))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"b64968612f6fa2c8f5c292a12a766ecc\")>\nmethod = <function url_to_be.<locals>._predicate at 0x7faac14ea8c0>\nmessage = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\n/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/selenium/webdriver/support/wait.py:105: TimeoutException\n\nDuring handling of the above exception, another exception occurred:\n\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"b64968612f6fa2c8f5c292a12a766ecc\")>\n\n    @pytest.fixture(scope=\"class\", autouse=True)\n    def setup(driver):\n        login_page = LoginPage(driver)\n    \n        with allure.step(\"Открытие страницы логина\"):\n            login_page.open(\"https://discord.com/login\")\n    \n            if not login_page.is_element_visible(LoginPage.EMAIL_INPUT):\n                raise AssertionError(\"Поле для ввода email не найдено.\")\n    \n        with allure.step(\"Вход в систему\"):\n>           login_page.login()\n\nconftest.py:57: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nlogin_page.py:48: in login\n    self.verify_login_success()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <login_page.LoginPage object at 0x7faac0ea7ca0>\n\n    @allure.step(\"Проверка перехода на страницу каналов\")\n    def verify_login_success(self):\n        try:\n            self.wait_for_url_to_be(LoginPage.CHANNELS_URL, timeout=20)\n            print(f\"Успешный вход: переход на {LoginPage.CHANNELS_URL}\")\n        except TimeoutException:\n            print(\"Ошибка: Не удалось перейти на страницу каналов после логина\")\n            self.take_screenshot(\"login_failed\")\n>           raise AssertionError(f\"Не удалось перейти на {LoginPage.CHANNELS_URL}\")\nE           AssertionError: Не удалось перейти на https://discord.com/channels/@me\n\nlogin_page.py:63: AssertionError","flaky":false,"newFailed":true,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"driver","time":{"start":1730127376986,"stop":1730127378439,"duration":1453},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup","time":{"start":1730127378439,"stop":1730127410083,"duration":31644},"status":"failed","statusMessage":"AssertionError: Не удалось перейти на https://discord.com/channels/@me\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/DiscordFrontEndSelenium/DiscordFrontEndSelenium/conftest.py\", line 57, in setup\n    login_page.login()\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/DiscordFrontEndSelenium/DiscordFrontEndSelenium/login_page.py\", line 48, in login\n    self.verify_login_success()\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/DiscordFrontEndSelenium/DiscordFrontEndSelenium/login_page.py\", line 63, in verify_login_success\n    raise AssertionError(f\"Не удалось перейти на {LoginPage.CHANNELS_URL}\")\n","steps":[{"name":"Открытие страницы логина","time":{"start":1730127378439,"stop":1730127380962,"duration":2523},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"Вход в систему","time":{"start":1730127380963,"stop":1730127410083,"duration":29120},"status":"failed","statusMessage":"AssertionError: Не удалось перейти на https://discord.com/channels/@me\n","statusTrace":"  File \"/home/runner/work/DiscordFrontEndSelenium/DiscordFrontEndSelenium/conftest.py\", line 57, in setup\n    login_page.login()\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/DiscordFrontEndSelenium/DiscordFrontEndSelenium/login_page.py\", line 48, in login\n    self.verify_login_success()\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/DiscordFrontEndSelenium/DiscordFrontEndSelenium/login_page.py\", line 63, in verify_login_success\n    raise AssertionError(f\"Не удалось перейти на {LoginPage.CHANNELS_URL}\")\n","steps":[{"name":"Вход в систему с зарегистрированными данными (аутентификация)","time":{"start":1730127380963,"stop":1730127410083,"duration":29120},"status":"failed","statusMessage":"AssertionError: Не удалось перейти на https://discord.com/channels/@me\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/DiscordFrontEndSelenium/DiscordFrontEndSelenium/login_page.py\", line 48, in login\n    self.verify_login_success()\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/DiscordFrontEndSelenium/DiscordFrontEndSelenium/login_page.py\", line 63, in verify_login_success\n    raise AssertionError(f\"Не удалось перейти на {LoginPage.CHANNELS_URL}\")\n","steps":[{"name":"Ввод email","time":{"start":1730127380963,"stop":1730127382264,"duration":1301},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"Ввод пароля","time":{"start":1730127382264,"stop":1730127383401,"duration":1137},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"Нажатие на кнопку Вход","time":{"start":1730127384402,"stop":1730127384452,"duration":50},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"Проверка успешного входа","time":{"start":1730127389457,"stop":1730127410083,"duration":20626},"status":"failed","statusMessage":"AssertionError: Не удалось перейти на https://discord.com/channels/@me\n","statusTrace":"  File \"/home/runner/work/DiscordFrontEndSelenium/DiscordFrontEndSelenium/login_page.py\", line 48, in login\n    self.verify_login_success()\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/DiscordFrontEndSelenium/DiscordFrontEndSelenium/login_page.py\", line 63, in verify_login_success\n    raise AssertionError(f\"Не удалось перейти на {LoginPage.CHANNELS_URL}\")\n","steps":[{"name":"Проверка перехода на страницу каналов","time":{"start":1730127389457,"stop":1730127410082,"duration":20625},"status":"failed","statusMessage":"AssertionError: Не удалось перейти на https://discord.com/channels/@me\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/DiscordFrontEndSelenium/DiscordFrontEndSelenium/login_page.py\", line 63, in verify_login_success\n    raise AssertionError(f\"Не удалось перейти на {LoginPage.CHANNELS_URL}\")\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":0,"hasContent":true}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":5,"attachmentsCount":0,"hasContent":true}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":6,"attachmentsCount":0,"hasContent":true}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":8,"attachmentsCount":0,"hasContent":true}],"afterStages":[{"name":"driver::0","time":{"start":1730127410157,"stop":1730127410244,"duration":87},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"tag","value":"order(2)"},{"name":"tag","value":"@pytest.mark.usefixtures('setup')"},{"name":"suite","value":"test_DiscordFrontEnd"},{"name":"subSuite","value":"TestDiscordMessageActions"},{"name":"host","value":"fv-az1442-469"},{"name":"thread","value":"2098-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test_DiscordFrontEnd"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"driver","value":"'chrome'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":1,"broken":8,"skipped":0,"passed":0,"unknown":0,"total":9},"items":[{"uid":"c8ee4791f96b91b6","reportUrl":"https://Helgi-P.github.io/DiscordFrontEndSelenium/9//#testresult/c8ee4791f96b91b6","status":"broken","statusDetails":"ValueError: Email или пароль не заданы в переменных окружения.","time":{"start":1730127335280,"stop":1730127335280,"duration":0}},{"uid":"cea2511acc770928","reportUrl":"https://Helgi-P.github.io/DiscordFrontEndSelenium/8//#testresult/cea2511acc770928","status":"broken","statusDetails":"ValueError: Email или пароль не заданы в переменных окружения.","time":{"start":1730127102884,"stop":1730127102884,"duration":0}},{"uid":"691265ad37f53b44","reportUrl":"https://Helgi-P.github.io/DiscordFrontEndSelenium/7//#testresult/691265ad37f53b44","status":"broken","statusDetails":"ValueError: Email или пароль не заданы в переменных окружения.","time":{"start":1730124453526,"stop":1730124453526,"duration":0}},{"uid":"e05f48e27bd9a944","reportUrl":"https://Helgi-P.github.io/DiscordFrontEndSelenium/6//#testresult/e05f48e27bd9a944","status":"broken","statusDetails":"ValueError: Email или пароль не заданы в переменных окружения.","time":{"start":1730123842399,"stop":1730123842399,"duration":0}},{"uid":"87c1a68728e3a18e","reportUrl":"https://Helgi-P.github.io/DiscordFrontEndSelenium/6//#testresult/87c1a68728e3a18e","status":"broken","statusDetails":"ValueError: Email или пароль не заданы в переменных окружения.","time":{"start":1730123686982,"stop":1730123686982,"duration":0}},{"uid":"d2ee95345c97ce77","reportUrl":"https://Helgi-P.github.io/DiscordFrontEndSelenium/5//#testresult/d2ee95345c97ce77","status":"broken","statusDetails":"TypeError: 'NoneType' object is not iterable","time":{"start":1730123224544,"stop":1730123224544,"duration":0}},{"uid":"66cc0c2aae49d42d","reportUrl":"https://Helgi-P.github.io/DiscordFrontEndSelenium/4//#testresult/66cc0c2aae49d42d","status":"broken","statusDetails":"TypeError: 'NoneType' object is not iterable","time":{"start":1730122254067,"stop":1730122254067,"duration":0}},{"uid":"3a82ae18d6f6e6a9","reportUrl":"https://Helgi-P.github.io/DiscordFrontEndSelenium/3//#testresult/3a82ae18d6f6e6a9","status":"broken","statusDetails":"TypeError: 'NoneType' object is not iterable","time":{"start":1730122001422,"stop":1730122001422,"duration":0}}]},"tags":["order(2)","@pytest.mark.usefixtures('setup')"]},"source":"cf6d1a844d9471c0.json","parameterValues":["'chrome'"]}